Traceback (most recent call last):
  File "/home/vinc/Bureau/Partage_ClassCord/server_classcord.py", line 107, in <module>
    main()
  File "/home/vinc/Bureau/Partage_ClassCord/server_classcord.py", line 99, in main
    server_socket.bind((HOST, PORT))
OSError: [Errno 98] Address already in use

